version: "3.9"
services:
  db:
    container_name: periodic-report-db
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql:delegated
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASS}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_PASSWORD=${DATABASE_PASS}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_HOST=${DATABASE_HOST}
    ports:
      - "3396:3306"

  server:
    build:
      context: .
    image: periodic-report/server
    container_name: periodic-report-server
    env_file: .env
    volumes:
      - ./:/app
    ports:
      - ${HOST_SERVER_PORT}:8000
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - db
    tty: true

volumes:
  mysql_data:
  python_packages: